### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by ItzDerock** [staudt/Genius#1]
I do not press a button when game starts but it thinks I do HELP PLZZ On home menu its fine.... It might be lack of mem

**Comment by staudt** [comment]
Are you using ports 1 or 2? If so, in many Arduinos they are also used for the internal LED, which can send extra signals, triggering button presses. Try ONLY using ports 3 and higher for both digital and analog. Let me know if that works ;)

**Comment by ItzDerock** [comment]
Im using pots 9, 10, 11. I am using a smaller chip then a Arduino uno so im thinking that there is not enough memory. Also I found a simpler version and that worked. :)

**Comment by sganzerla** [comment]
Hi @GamerDerock, if you using protoboard like it image, try to join the two board negative.

![image](https://user-images.githubusercontent.com/22710963/75208806-754f6780-575b-11ea-9a96-5695e436d3ff.png)
